services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: app_db
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=db
    depends_on:
      - db

volumes:
  db_data:
